site_url: https://source.d3l2hvqu0x0axr.amplifyapp.com/
logo_url: https://source.d3l2hvqu0x0axr.amplifyapp.com/assets/icon/favicon.ico

backend:
  # Use custom Oauth server on AWS as backend
  name: github
  repo: chrsmlls333/storylog
  branch: source
  squash_merges: true

  # Commit message templates
  commit_messages:
    create: '[CMS] Create {{collection}} “{{slug}}”'
    update: '[CMS] Update {{collection}} “{{slug}}”'
    delete: '[CMS] Delete {{collection}} “{{slug}}”'
    uploadMedia: '[CMS] Upload “{{path}}”'
    deleteMedia: '[CMS] Delete “{{path}}”'
    openAuthoring: '[CMS] {{message}}'

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

# Please run "npx netlify-cms-proxy-server" for local backend
local_backend: true

publish_mode: editorial_workflow

collections: 

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "Post"
    description: >
      The description is a great place for tone setting, high level information, and editing
      guidelines that are specific to a collection.
    folder: "content/_posts"
    summary: '{{year}}/{{month}}/{{day}}: {{title}}'
    create: true # Allow users to create new documents in this collection
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: 'posts/{{year}}-{{month}}-{{day}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string", default: "Status Update"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      # - label: "Tags"
      #   name: "tags"
      #   widget: "create-select"
      #   mode: html
      #   url: /tags
      #   query: "h2.tag-title"
      #   attribute: "data-tag"
      #   multiple: true
      - label: 'Tags'
        name: 'tags'
        widget: 'create-select'
        mode: 'plain'
        url: '/tags.txt'
        multiple: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: [ bold, italic, code, link, heading-one, heading-two, heading-three, heading-four, heading-five, heading-six, quote, bulleted-list, numbered-list ]
        editor_components: [ youtube, image-figure, more ]
      - label: "Redirects"
        hint: "Here you can list local urls (beginning with a /) that should also be created to redirect here. Comma-separated."
        name: redirect_from
        widget: list
        allow_add: true
        required: false
      - label: "Links"
        name: links 
        widget: object 
        fields:
        - label: "DeviantArt Post"
          name: deviantart
          widget: "string"
          required: false
          hint: "Add a complete URL to suggest readers comment on a DeviantArt post."


  - name: stories
    label: Stories
    label_singular: Story
    description: >
      These Stories are like data files, used primarily to assemble Chapters into folios. Create a Story here then go get writing!
    folder: "content/_stories"
    summary: '{{title}}'
    view_groups: 
      - label: Author
        field: author
      - label: Complete
        field: complete
      - label: Type
        field: type
    create: true
    editor:
      preview: false
    slug: "{{fields.slug}}"
    preview_path: '/stories/full/{{slug}}'
    fields: # The fields for each document, usually in front matter
      - {label: "Story/Series Title", name: "title", widget: "string", required: true, hint: ''}
      - {label: "Slug Identifier", name: "slug", widget: "string", required: true, pattern: ['^[a-z0-9-_]{4,}$', "Must have only lowercase ASCII characters, and not too short."], hint: 'Use no spaces or special characters, only (0-9, a-z, _, -, ~)'}
      - {label: "Author", name: "author", widget: "string", required: true, default: ''}
      - {label: "Editor", name: "editor", widget: "string", required: false, hint: 'Either to mark my participation in a Guest Story or attribute a friend.'}
      - {label: "Patron", name: "patron", widget: "string", required: false, hint: 'Relevant to commissions/gifts only.'}
      - label: Story Complete
        name: complete
        widget: boolean
        default: false
        required: true
      - label: Story Type
        name: type
        widget: select
        multiple: false
        required: false
        options:
          - { label: "Commission", value: "commission" }
          - { label: "Guest/Repost", value: "guest" }
          - { label: "Collaboration", value: "collaboration" }
      # - label: "Tags"
      #   name: "tags"
      #   # hint: 'Do not duplicate any tags you would rather add for the whole Story!'
      #   widget: "create-select"
      #   mode: html
      #   url: /tags
      #   query: "h2.tag-title"
      #   attribute: "data-tag"
      #   multiple: true
      - label: 'Tags'
        name: 'tags'
        widget: 'create-select'
        mode: 'plain'
        url: '/tags.txt'
        multiple: true
      - label: "Description"
        name: "description"
        hint: 'This is what readers will find on the Stories table of contents, make it good-ish.'
        widget: "markdown"
        minimal: false
        buttons: [ bold, italic, code, link, quote, bulleted-list, numbered-list ]
      - label: "Disclaimer"
        name: "disclaimer"
        hint: 'Disclaimer or warning shown at the start of each chapter and on the Stories listing.'
        widget: "markdown"
        minimal: true
        buttons: [ link ]
        editor_components: []
        required: false
      - label: "Endnote"
        name: "endnote"
        hint: 'Note shown at the tail end of each chapter, usually for a shoutout or link.'
        widget: "markdown"
        minimal: true
        buttons: [ link ]
        editor_components: []
        required: false
      - name: forcestorylink
        label: Skip the Chapters List
        hint: "Skip printing the chapter list on Stories page, instead only 'Read the Story...', like single-chapter behaviour."
        widget: boolean
        required: false
      - name: watermark
        label: Watermark
        hint: 'Displayed on Stories page behind text.'
        widget: object
        summary: "{{fields.image}}"
        collapsed: true
        fields:
        - name: image
          label: Watermark Image
          # hint: 'Displayed on Stories page behind text.'
          widget: image
          media_folder: "/assets/images/watermarks"
          choose_url: true
          allow_multiple: false
          required: false
        - name: opacity
          label: Watermark Opacity
          hint: 'Override for adjusting heavy images further into the background.'
          widget: number
          value_type: float
          min: 0
          max: 1
          step: 0.01
          required: false
      - label: "Redirects"
        hint: "Here you can list local urls (beginning with a /) that should also be created to redirect here. Comma-separated."
        name: redirect_from
        widget: list
        allow_add: true
        required: false


  - name: chapters
    label: Chapters
    label_singular: Chapter
    description: >
      These chapters rely on Story entries to be listed and assembled into navigable pages. Make sure to create a Story with the same title as this chapter's Series!
    folder: "content/_chapters"
    summary: '{{series}} · {{part}} · {{entry}}'
    view_groups: 
      - label: Series
        field: series
      - label: Year
        field: date
        pattern: \d{4}
    create: true
    editor:
      preview: true
    identifier_field: entry
    slug: "{{fields.slug}}"
    preview_path: '/stories/chapters/{{slug}}'
    fields: # The fields for each document, usually in front matter
      # - {label: "Series Title", name: "series", widget: "string", required: true, hint: 'For one-shot stories, name this the same as the Chapter Title'}
      - label: "Series Title"
        name: "series"
        widget: "relation"
        collection: stories
        value_field: title
        search_fields: [ title ]
        required: true
        hint: 'For one-shot stories, name this the same as the Chapter Title'
      - {label: "Part Title", name: "part", widget: "string", required: false, hint: 'Please follow the convention of "Part #". For standalone parts or separation, name this the same as Chapter Title'}
      - {label: "Chapter Title", name: "entry", widget: "string", required: true, hint: 'Please follow the convention of "Chapter #"'}
      - {label: "Slug Identifier", name: "slug", widget: "string", required: true, pattern: ['^[a-z0-9-_]{4,}$', "Must have only lowercase ASCII characters, and not too short."], hint: 'Use no spaces or special characters, only (0-9, a-z, _, -, ~)'}
      - {label: "Summary", name: "description", widget: "string", required: false, hint: 'This is where a small summary or headline can go.'}
      - {label: "Publish Date", name: "date", widget: "datetime", required: true}
      # - label: "Tags"
      #   name: "tags"
      #   hint: 'Do not duplicate any tags you would rather add for the whole Story!'
      #   widget: "create-select"
      #   mode: html
      #   url: /tags
      #   query: "h2.tag-title"
      #   attribute: "data-tag"
      #   multiple: true
      #   required: false
      - label: 'Tags'
        name: 'tags'
        widget: 'create-select'
        mode: 'plain'
        url: '/tags.txt'
        multiple: true
        hint: 'Do not duplicate any tags you would rather add for the whole Story!'
        required: false
      - label: "Body"
        name: "body"
        widget: "markdown"
        buttons: [ bold, italic, code, link, heading-one, heading-two, heading-three, heading-four, heading-five, heading-six, quote, bulleted-list, numbered-list ]
        editor_components: [ image-figure ]
      - label: "Redirects"
        hint: "Here you can list local urls (beginning with a /) that should also be created to redirect here. Comma-separated."
        name: redirect_from
        widget: list
        allow_add: true
        required: false
      - label: "Links"
        name: links 
        widget: object 
        fields:
          - label: "DeviantArt Post"
            name: deviantart
            widget: "string"
            required: false
            hint: "Add a complete URL to suggest readers comment on a DeviantArt post."


  - label: "Data"
    name: "data"
    # description: >
    #   These variables are largely for updating selection lists in individual posts. Add tags and other queries here before using them in new posts.
    editor:
      preview: false
    files: 
      - label: Text Strings (for Pages)
        name: text
        file: _data/text.yml
        fields:
          - label: Home Page
            name: index
            widget: object
            fields:
              - label: Intro Text
                name: intro
                widget: "markdown"
                buttons: [ bold, italic, link, heading-one, heading-two, heading-three, heading-four, heading-five, heading-six, quote, bulleted-list, numbered-list ]
                editor_components: []
                minimal: true
                required: true
              - label: Adult Warning
                hint: First line will be bold and underlined.
                name: adult_warning
                widget: "markdown"
                buttons: [ bold, italic, link ]
                editor_components: []
                minimal: true
                required: true
          - label: Tags Page
            name: tags
            widget: object
            fields:
              - label: Intro Text
                name: intro
                widget: "markdown"
                buttons: [ bold, italic, link, heading-one, heading-two, heading-three, heading-four, heading-five, heading-six, quote, bulleted-list, numbered-list ]
                editor_components: []
                minimal: true
                required: true

      